spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2MB
      location: D:/custom_temp
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:mysql://localhost/receipt"
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}  # 실제MySQL 비밀번호 입력
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #   create-drop none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: messages
  jwt:
    secret-key: ${JWT_SECRET_KEY}

receipt:
  image-path: D:/custom_temp

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG  # Spring Security 로그를 DEBUG 수준으로 설정

clova:
  ocr:
    client-id: "sm6pcc5t4e" # 발급받은 Client ID
    client-secret: "SHZ5cmNhZ2lnTlhPWEZ4WmdpdkJ4SVFIa0JvekRxemY=" # 발급받은 Client Secret
    url: "https://djyhuy4mnd.apigw.ntruss.com/custom/v1/35910/c9c51c7e47ecae4852bf3de8a921c33abd6369260f7538fd01fe2f4cd5f90676/document/receipt" # Clova OCR API URL
---
spring:
  ervlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://3.36.81.80:3306/receipt"
    username: "root"
    password: "102604jh#*" # 실제 MySQL 비밀번호 입력
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none #   create-drop none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: messages
  jwt:
    secret-key: ${JWT_SECRET_KEY}

receipt:
  image-path: "/home/ec2-user/receipt-app/uploads/"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG  # Spring Security 로그를 DEBUG 수준으로 설정

clova:
  ocr:
    client-id: "sm6pcc5t4e" # 발급받은 Client ID
    client-secret: "SHZ5cmNhZ2lnTlhPWEZ4WmdpdkJ4SVFIa0JvekRxemY=" # 발급받은 Client Secret
    url: "https://djyhuy4mnd.apigw.ntruss.com/custom/v1/35910/c9c51c7e47ecae4852bf3de8a921c33abd6369260f7538fd01fe2f4cd5f90676/document/receipt" # Clova OCR API URL