spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/receipt
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  messages:
    basename: messages
  jwt:
    secret-key: aimlproject

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG  # Spring Security 로그를 DEBUG 수준으로 설정

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://3.36.81.80:3306/receipt"
    username: "root"
    password: "102604jh#*"  # 실제 MySQL 비밀번호 입력
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: messages
  jwt:
    secret-key: aimlproject

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG  # Spring Security 로그를 DEBUG 수준으로 설정
