name: Deploy Receipt-App to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'receipt-app/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # 1. Repository Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. SSH Key 설정
      - name: Configure SSH Key
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" > ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config

      # 3. Build with Gradle
      - name: Build with Gradle
        run: |
          cd receipt-app
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # 4. Transfer JAR file to EC2
      - name: Transfer JAR to EC2
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: receipt-app/build/libs/receipt-app-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/AIML_project/receipt-app/build/libs/

      # 5. Restart the application on EC2
      - name: Restart application on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            LOG_FILE=~/deployment.log
            APP_LOG_FILE=~/receipt-app.log
            JAR_NAME=receipt-app-0.0.1-SNAPSHOT.jar

            echo "Stopping existing application..." >> $LOG_FILE
            pkill -f "$JAR_NAME" || true
            sleep 3

            echo "Starting new application..." >> $LOG_FILE
            nohup java -jar /home/ec2-user/AIML_project/receipt-app/build/libs/$JAR_NAME --spring.profiles.active=dev >> $APP_LOG_FILE 2>&1 &
            echo "Deployment completed!" >> $LOG_FILE
            tail -n 20 $LOG_FILE
