name: Deploy Receipt-App to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'receipt-app/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build receipt-app with Gradle
        run: |
          cd receipt-app
          chmod +x gradlew
          ./gradlew build -x test

      - name: Deploy receipt-app to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Starting SSH Key Debugging..."
          echo "Printing first few lines of PRIVATE_KEY for verification:"
          echo "$PRIVATE_KEY" | head -n 5

          echo "Writing SSH key to private_key.pem"
          echo -e "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          echo "Validating private key file..."
          if ! ssh-keygen -y -f private_key.pem > /dev/null 2>&1; then
            echo "Private key validation failed. Please check your SSH key format."
            exit 1
          fi
          echo "Private key file validation passed!"

          echo "Checking SSH connection to $HOST..."
          ssh -v -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST "echo 'SSH connection 성공'"
          if [ $? -ne 0 ]; then
            echo "SSH connection 실패"
            exit 1
          fi

          echo "Deploying application"
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd AIML_project/receipt-app
            echo "Pulling latest changes from GitHub..."
            git pull origin main
            echo "Building the application..."
            ./gradlew build -x test
            echo "Stopping existing application process..."
            pkill -f 'receipt-app-0.0.1-SNAPSHOT.jar' || true
            echo "Starting new application instance..."
            nohup java -jar build/libs/receipt-app-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev >> nohup.out 2>&1 &
            echo "Deployment completed!"
          EOF

          echo "Cleaning up SSH key file"
          rm -f private_key.pem
