name: Deploy Receipt-App to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'receipt-app/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 전체 타임아웃 60분으로 설정

    steps:
      # 1. Repository Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Build the application
      - name: Build with Gradle
        run: |
          cd receipt-app
          chmod +x ./gradlew
          ./gradlew clean build -x test
          ls -al build/libs  # 빌드 산출물 확인

      # 3. Disable strict host key checking
      - name: Disable strict host key checking
        run: |
          mkdir -p ~/.ssh
          echo "Host *" > ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      # 4. Transfer JAR to EC2 using SCP
      - name: Transfer JAR file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: receipt-app/build/libs/receipt-app-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/AIML_project/receipt-app/build/libs/

      # 5. Restart the application on EC2
      - name: Restart application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            JAR_NAME=receipt-app-0.0.1-SNAPSHOT.jar
            
            # 메모리 캐시 정리
            sudo sync; echo 3 | sudo tee /proc/sys/vm/drop_caches
            
            # 기존 프로세스 종료
            PIDS=$(pgrep -f "$JAR_NAME")
            if [ -n "$PIDS" ]; then
              kill -9 $PIDS
            fi
            
            # 메모리 최적화 JVM 설정 적용
            nohup java -Xms64m -Xmx128m -XX:+UseZGC -jar /home/ec2-user/AIML_project/receipt-app/build/libs/$JAR_NAME --spring.profiles.active=dev >/dev/null 2>&1 &
