name: Deploy Receipt-App to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'receipt-app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known host
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o ServerAliveInterval=120 -o ServerAliveCountMax=120 -tt -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} <<EOF
set -e

LOG_FILE=~/deployment.log

echo "=== Deploying application ===" > $LOG_FILE

echo "Navigating to application directory..." >> $LOG_FILE
cd AIML_project/receipt-app || exit 1

echo "Pulling latest changes from GitHub..." >> $LOG_FILE
git pull origin main >> $LOG_FILE 2>&1

echo "Building the application..." >> $LOG_FILE
./gradlew build -x test >> $LOG_FILE 2>&1
BUILD_STATUS=$?
if [ $BUILD_STATUS -ne 0 ]; then
  echo "Build failed with status $BUILD_STATUS" >> $LOG_FILE
  exit 1
fi
echo "Build completed successfully." >> $LOG_FILE

echo "Stopping existing application process..." >> $LOG_FILE
PIDS=\$(pgrep -f 'receipt-app-0.0.1-SNAPSHOT.jar')
if [ -n "\$PIDS" ]; then
  echo "Existing process found: \$PIDS" >> $LOG_FILE
  kill -9 \$PIDS >> $LOG_FILE 2>&1
  sleep 3
  PIDS_CHECK=\$(pgrep -f 'receipt-app-0.0.1-SNAPSHOT.jar')
  if [ -n "\$PIDS_CHECK" ]; then
    echo "Force killing remaining processes..." >> $LOG_FILE
    kill -9 \$PIDS_CHECK >> $LOG_FILE 2>&1
  fi
  echo "Process \$PIDS killed." >> $LOG_FILE
else
  echo "No existing process found." >> $LOG_FILE
fi
sleep 3

echo "Starting new application instance..." >> $LOG_FILE
nohup setsid java -jar build/libs/receipt-app-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev >> ~/receipt-app.log 2>&1 &
disown
echo "Application started with PID \$!" >> $LOG_FILE
sleep 5

echo "Deployment completed!" >> $LOG_FILE
ps aux | grep 'receipt-app-0.0.1-SNAPSHOT.jar' >> $LOG_FILE
echo "Application log (last 20 lines):" >> $LOG_FILE
tail -n 20 ~/receipt-app.log >> $LOG_FILE

cat $LOG_FILE
EOF
