name: Deploy Receipt-App to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'receipt-app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. SSH 키 설정
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3. EC2 서버의 공개 키 등록
      - name: Add known host
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 4. EC2에 접속하여 애플리케이션 배포
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -tt -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # 오류 발생 시 즉시 종료
      
            echo "Navigating to application directory..."
            cd AIML_project/receipt-app || exit 1
      
            echo "Pulling latest changes from GitHub..."
            git pull origin main
      
            echo "Building the application..."
            ./gradlew build -x test
      
            echo "Stopping existing application process..."
            PIDS=\$(pgrep -f 'receipt-app-0.0.1-SNAPSHOT.jar')
            if [ -n "\$PIDS" ]; then
              echo "Existing process found: \$PIDS"
              kill -9 \$PIDS
              echo "Process \$PIDS killed."
            else
              echo "No existing process found."
            fi
            sleep 3
      
            echo "Starting new application instance..."
            nohup java -jar build/libs/receipt-app-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev > ~/receipt-app.log 2>&1 &
            echo "Application started in background."
      
            sleep 5  # 애플리케이션 실행 대기
      
            echo "Checking running processes..."
            ps aux | grep 'receipt-app-0.0.1-SNAPSHOT.jar'
            echo "Last 20 lines of application log:"
            tail -n 20 ~/receipt-app.log
          EOF
